/**
 * Installation Guide - Wall-based Cabinet Installation Guide System
 * 100% PORT from AppScript installationguide.js
 *
 * Uses plank_id directly from "visual data" / "raw data" (NO lookup from Formatted_Plank_Data)
 * Wall → Box → Plank hierarchy
 * Material color coding
 * Step-by-step assembly
 *
 * ALTERATION FROM APPSCRIPT: Only I/O changed.
 *   - Input: rawValues (2D array, first row = headers)
 *   - Output: VisualizationData (hierarchy of walls/boxes/planks)
 *   - Position/dimension updates operate on in-memory arrays
 *   - No SpreadsheetApp, no HtmlService
 */

// =================================================================
// =================== TYPES ===================
// =================================================================

export interface Position {
  x: number;
  y: number;
  z: number;
}

export interface Dimensions {
  lenX: number;
  lenY: number;
  lenZ: number;
}

export interface PlankData {
  id: string;
  entityName: string;
  material: string;
  materialColor: string;
  position: Position;
  dimensions: Dimensions;
  role: string;
  explodeDirection: Position;
  assemblyDirection: { arrow: string; text: string };
  isDoor: boolean;
  hingeSide: string;
  assemblyOrder: number;
  autoGenerated: boolean;
  rowIndex: number;
  stepNumber?: number;
}

export interface ChecklistItem {
  id: string;
  name: string;
  material: string;
  dimensions: string;
  checked: boolean;
}

export interface BoxData {
  id: string;
  entityName: string;
  roomName: string;
  unitLocation: string;
  boxModel: string;
  boxType: string;
  position: Position;
  dimensions: Dimensions;
  planks: PlankData[];
  checklist: ChecklistItem[];
  rowIndex: number;
  totalSteps?: number;
}

export interface WallData {
  id: string;
  entityName: string;
  roomName: string;
  unitLocation: string;
  material: string;
  position: Position;
  dimensions: Dimensions;
  boxes: BoxData[];
  rowIndex: number;
}

export interface MaterialLegendItem {
  name: string;
  color: string;
}

export interface VisualizationData {
  walls: WallData[];
  materialLegend: MaterialLegendItem[];
  summary: {
    totalWalls: number;
    totalBoxes: number;
    totalPlanks: number;
    timestamp: string;
    autoGeneratedIds: number;
  };
}

// =================================================================
// =================== HEADER PARSING ===================
// =================================================================

function parseHeaders(headerRow: unknown[]): Record<string, number> | null {
  const rawHeaders = headerRow.map((h) => (h || '').toString().trim());
  const lowerHeaders = rawHeaders.map((h) => h.toLowerCase().replace(/\s+/g, ' '));
  const headerIndex: Record<string, number> = {};

  lowerHeaders.forEach((h, i) => {
    const normalized = h.replace(/[\s_]/g, '');

    if (normalized === 'entityname' || h === 'entity name' || h === 'entity_name')
      headerIndex['entity name'] = i;
    if (normalized === 'level' || h === 'level') headerIndex['level'] = i;
    if (normalized === 'material' || h === 'material') headerIndex['material'] = i;
    if (normalized === 'roomname' || h === 'room_name' || h === 'room name')
      headerIndex['room_name'] = i;
    if (normalized === 'unitlocation' || h === 'unit_location' || h === 'unit location')
      headerIndex['unit_location'] = i;
    if (normalized === 'boxmodel' || h === 'box_model' || h === 'box model')
      headerIndex['box_model'] = i;
    if (normalized === 'boxtype' || h === 'box_type' || h === 'box type')
      headerIndex['box_type'] = i;
    if (h === 'x') headerIndex['x'] = i;
    if (h === 'y') headerIndex['y'] = i;
    if (h === 'z') headerIndex['z'] = i;
    if (normalized === 'lenx' || h === 'len_x' || h === 'len x') headerIndex['lenx'] = i;
    if (normalized === 'leny' || h === 'len_y' || h === 'len y') headerIndex['leny'] = i;
    if (normalized === 'lenz' || h === 'len_z' || h === 'len z') headerIndex['lenz'] = i;
    if (normalized === 'plankid' || h === 'plank_id' || h === 'plank id')
      headerIndex['plank_id'] = i;
  });

  const requiredHeaders = [
    'level', 'entity name', 'material', 'room_name', 'unit_location',
    'box_model', 'box_type', 'x', 'y', 'z', 'lenx', 'leny', 'lenz',
    'plank_id',
  ];

  const missing = requiredHeaders.filter((req) => headerIndex[req] === undefined);
  if (missing.length > 0) {
    console.warn('Missing headers:', missing.join(', '));
    return null;
  }

  return headerIndex;
}

function parseNumber(value: unknown): number {
  const cleaned = String(value).replace(/[^0-9.\-]/g, '');
  const n = parseFloat(cleaned);
  return isNaN(n) ? 0 : n;
}

// =================================================================
// =================== HIERARCHY BUILDER ===================
// =================================================================

function buildHierarchy(
  values: unknown[][],
  headerIndex: Record<string, number>
): VisualizationData {
  const walls: WallData[] = [];
  let currentWall: WallData | null = null;
  let currentBox: BoxData | null = null;
  let globalBoxId = 1;
  let wallId = 1;

  for (let r = 1; r < values.length; r++) {
    const row = values[r];
    if ((row as unknown[]).every((cell) => String(cell).trim() === '')) continue;

    const level = String(row[headerIndex['level']]).trim().toLowerCase();
    const entityName = String(row[headerIndex['entity name']] || '').trim();
    const material = String(row[headerIndex['material']] || '').trim();
    const roomName = String(row[headerIndex['room_name']] || '').trim();
    const unitLocation = String(row[headerIndex['unit_location']] || '').trim();
    const boxModel = String(row[headerIndex['box_model']] || '').trim();
    const boxType = String(row[headerIndex['box_type']] || '').trim();

    const X = parseNumber(row[headerIndex['x']]);
    const Y = parseNumber(row[headerIndex['y']]);
    const Z = parseNumber(row[headerIndex['z']]);
    const lenX = parseNumber(row[headerIndex['lenx']]);
    const lenY = parseNumber(row[headerIndex['leny']]);
    const lenZ = parseNumber(row[headerIndex['lenz']]);

    const rawPlankId = row[headerIndex['plank_id']];
    const plankId =
      rawPlankId !== undefined && rawPlankId !== null && String(rawPlankId).trim() !== ''
        ? String(rawPlankId).trim()
        : null;

    if (level === '0' || level === 'wall') {
      if (currentWall) walls.push(currentWall);
      currentWall = {
        id: `wall_${wallId++}`,
        entityName,
        roomName,
        unitLocation,
        material,
        position: { x: X, y: Y, z: Z },
        dimensions: { lenX: lenX || 5000, lenY: lenY || 200, lenZ: lenZ || 3000 },
        boxes: [],
        rowIndex: r + 1,
      };
      currentBox = null;
    } else if ((level === '1' || level.startsWith('box')) && currentWall) {
      currentBox = {
        id: `box_${globalBoxId++}`,
        entityName,
        roomName,
        unitLocation,
        boxModel,
        boxType,
        position: { x: X, y: Y, z: Z },
        dimensions: { lenX, lenY, lenZ },
        planks: [],
        checklist: [],
        rowIndex: r + 1,
      };
      currentWall.boxes.push(currentBox);
    } else if ((level === '2' || level.startsWith('plank')) && currentBox) {
      if (lenX <= 0 || lenY <= 0 || lenZ <= 0) continue;

      const plankRole = determinePlankRole(entityName);
      const materialColor = getMaterialColor(material);

      const plank: PlankData = {
        id: plankId || 'NO ID',
        entityName,
        material,
        materialColor,
        position: { x: X, y: Y, z: Z },
        dimensions: { lenX, lenY, lenZ },
        role: plankRole,
        explodeDirection: getExplodeDirection(plankRole),
        assemblyDirection: getAssemblyDirection(plankRole),
        isDoor: plankRole === 'door',
        hingeSide: determineHingeSide(entityName),
        assemblyOrder: getAssemblyOrder(plankRole),
        autoGenerated: false,
        rowIndex: r + 1,
      };

      currentBox.planks.push(plank);
      currentBox.checklist.push({
        id: plank.id,
        name: entityName,
        material,
        dimensions: `${lenX} × ${lenY} × ${lenZ}`,
        checked: false,
      });
    }
    // Level 3 (holes/operations) — ignored for installation guide
  }

  if (currentWall) walls.push(currentWall);

  walls.forEach((wall) => {
    wall.boxes.forEach((box) => {
      box.planks.sort((a, b) => a.assemblyOrder - b.assemblyOrder);
      box.planks.forEach((plank, index) => {
        plank.stepNumber = index + 1;
      });
      box.totalSteps = box.planks.length;
    });
  });

  const totalBoxes = walls.reduce((sum, w) => sum + w.boxes.length, 0);
  const totalPlanks = walls.reduce(
    (sum, w) => sum + w.boxes.reduce((s, b) => s + b.planks.length, 0),
    0
  );

  const materialsSet = new Set<string>();
  walls.forEach((wall) => {
    wall.boxes.forEach((box) => {
      box.planks.forEach((plank) => {
        if (plank.material) materialsSet.add(plank.material);
      });
    });
  });

  const materialLegend: MaterialLegendItem[] = Array.from(materialsSet).map((mat) => ({
    name: mat,
    color: getMaterialColor(mat),
  }));

  return {
    walls,
    materialLegend,
    summary: {
      totalWalls: walls.length,
      totalBoxes,
      totalPlanks,
      timestamp: new Date().toISOString(),
      autoGeneratedIds: 0,
    },
  };
}

// =================================================================
// =================== HELPER FUNCTIONS ===================
// =================================================================

function determinePlankRole(entityName: string): string {
  const name = entityName.toLowerCase();
  if (name.includes('door')) return 'door';
  if (name.includes('bottom')) return 'bottom';
  if (name.includes('top')) return 'top';
  if (name.includes('left')) return 'left';
  if (name.includes('right')) return 'right';
  if (name.includes('back')) return 'back';
  if (name.includes('front')) return 'front';
  if (name.includes('shelf') || name.includes('plank')) return 'shelf';
  if (name.includes('skirting')) return 'skirting';
  if (name.includes('facia') || name.includes('fascia')) return 'facia';
  if (name.includes('draw') || name.includes('drawer')) return 'drawer';
  if (name.includes('dummy')) return 'dummy';
  return 'other';
}

function getExplodeDirection(role: string): Position {
  const d = 600;
  switch (role) {
    case 'left': return { x: -d, y: 0, z: 0 };
    case 'right': return { x: d, y: 0, z: 0 };
    case 'top': return { x: 0, y: 0, z: d };
    case 'bottom': return { x: 0, y: 0, z: -d };
    case 'back': return { x: 0, y: d, z: 0 };
    case 'front':
    case 'door': return { x: 0, y: -d, z: 0 };
    case 'shelf': return { x: 0, y: -d * 0.5, z: 0 };
    case 'skirting': return { x: 0, y: -d * 0.3, z: -d * 0.3 };
    case 'drawer': return { x: 0, y: -d * 0.7, z: 0 };
    default: return { x: 0, y: -d * 0.4, z: 0 };
  }
}

function getAssemblyDirection(role: string): { arrow: string; text: string } {
  switch (role) {
    case 'left': return { arrow: '→', text: 'Place LEFT' };
    case 'right': return { arrow: '←', text: 'Place RIGHT' };
    case 'top': return { arrow: '↓', text: 'Place on TOP' };
    case 'bottom': return { arrow: '↑', text: 'Place at BOTTOM' };
    case 'back': return { arrow: '⟵', text: 'Place at BACK' };
    case 'front':
    case 'door': return { arrow: '⟶', text: 'Attach FRONT' };
    case 'shelf': return { arrow: '—', text: 'Insert SHELF' };
    case 'skirting': return { arrow: '↓', text: 'Fix SKIRTING' };
    case 'drawer': return { arrow: '⟶', text: 'Slide DRAWER' };
    default: return { arrow: '•', text: 'Place part' };
  }
}

function getAssemblyOrder(role: string): number {
  const orderMap: Record<string, number> = {
    skirting: 1, bottom: 2, left: 3, right: 4,
    back: 5, top: 6, shelf: 7, dummy: 8,
    facia: 9, drawer: 10, front: 11, door: 12, other: 7,
  };
  return orderMap[role] || 7;
}

function determineHingeSide(entityName: string): string {
  const name = entityName.toLowerCase();
  if (name.includes('left') || name.includes('_l')) return 'left';
  if (name.includes('right') || name.includes('_r')) return 'right';
  const doorMatch = name.match(/door\s*(\d+)/i);
  if (doorMatch) {
    return parseInt(doorMatch[1]) % 2 === 1 ? 'left' : 'right';
  }
  return 'right';
}

const MATERIAL_COLOR_MAP: Record<string, string> = {
  '2632 SF Inner': '#E07020',
  'BB EHGP 701': '#2196F3',
  '7070': '#8BC34A',
  'EHGP 701': '#00BCD4',
  'Color (Kitchen)': '#FF5722',
  'MDF': '#9C27B0',
  'HDF': '#3F51B5',
  'Plywood': '#FF9800',
  'Particle Board': '#009688',
  'BWP': '#F44336',
  'BWR': '#4CAF50',
  'Marine Ply': '#03A9F4',
  'White': '#E0E0E0',
  'Ivory': '#FFF8E1',
  'Teak': '#8D6E63',
  'Walnut': '#5D4037',
  'Oak': '#FFB74D',
  'Maple': '#FFF176',
  'Cherry': '#C62828',
  'Mahogany': '#6D4C41',
  'Pine': '#AED581',
  'Wenge': '#37474F',
  'Ash': '#B0BEC5',
};

const FALLBACK_COLORS = [
  '#E91E63', '#673AB7', '#2196F3', '#00BCD4', '#4CAF50', '#CDDC39',
  '#FF9800', '#795548', '#607D8B', '#F44336', '#9C27B0', '#3F51B5',
];

function hashString(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) {
    h = ((h << 5) - h + s.charCodeAt(i)) | 0;
  }
  return Math.abs(h);
}

function getMaterialColor(material: string): string {
  const m = (material || '').trim();
  if (MATERIAL_COLOR_MAP[m]) return MATERIAL_COLOR_MAP[m];
  const lower = m.toLowerCase();
  for (const [key, color] of Object.entries(MATERIAL_COLOR_MAP)) {
    if (lower.includes(key.toLowerCase())) return color;
  }
  return FALLBACK_COLORS[hashString(m) % FALLBACK_COLORS.length];
}

export { MATERIAL_COLOR_MAP };

// =================================================================
// =================== MAIN FUNCTION ===================
// =================================================================

/**
 * 100% port of AppScript showVisualization().
 * Input: rawValues (2D array, first row = headers).
 * Output: VisualizationData hierarchy.
 */
export function buildInstallationGuide(rawValues: unknown[][]): VisualizationData {
  if (!rawValues || rawValues.length < 2) {
    throw new Error('The data is empty or has only a header row.');
  }

  const headerIndex = parseHeaders(rawValues[0]);
  if (!headerIndex) {
    throw new Error('Required columns not found in the data.');
  }

  return buildHierarchy(rawValues, headerIndex);
}

/**
 * Cross-reference plank IDs with pipeline formatted data to get clean material codes.
 * Raw data has composite strings like "BB EHGP 701 CBR"; formatted data has the clean code.
 */
export function enrichMaterialFromPipeline(
  vizData: VisualizationData,
  formattedData: { header: string[]; rows: unknown[][] }
): VisualizationData {
  const idIdx = formattedData.header.indexOf('plank_id');
  const matIdx = formattedData.header.indexOf('plank_material');
  if (idIdx === -1 || matIdx === -1) return vizData;

  const materialMap = new Map<string, string>();
  for (const row of formattedData.rows) {
    const id = String(row[idIdx] ?? '').trim();
    const mat = String(row[matIdx] ?? '').trim();
    if (id && mat) materialMap.set(id, mat);
  }

  const materialsSet = new Set<string>();
  for (const wall of vizData.walls) {
    for (const box of wall.boxes) {
      for (const plank of box.planks) {
        const cleanMat = materialMap.get(plank.id);
        if (cleanMat) {
          plank.material = cleanMat;
          plank.materialColor = getMaterialColor(cleanMat);
        }
        if (plank.material) materialsSet.add(plank.material);
      }
    }
  }

  vizData.materialLegend = Array.from(materialsSet).map((mat) => ({
    name: mat,
    color: getMaterialColor(mat),
  }));

  return vizData;
}

/**
 * Port of updatePlankPosition — operates on in-memory data.
 */
export function updatePlankPositionInData(
  rawValues: unknown[][],
  rowIndex: number,
  newX: number,
  newY: number,
  newZ: number
): { success: boolean; error?: string } {
  if (!rawValues || rawValues.length === 0) {
    return { success: false, error: 'Data is empty' };
  }

  const headers = rawValues[0];
  const lowerHeaders = (headers as unknown[]).map((h) =>
    (h || '').toString().trim().toLowerCase()
  );

  const xCol = lowerHeaders.indexOf('x');
  const yCol = lowerHeaders.indexOf('y');
  const zCol = lowerHeaders.indexOf('z');

  if (rowIndex < 1 || rowIndex >= rawValues.length) {
    return { success: false, error: 'Row index out of range' };
  }

  if (xCol >= 0) (rawValues[rowIndex] as unknown[])[xCol] = newX + ' mm';
  if (yCol >= 0) (rawValues[rowIndex] as unknown[])[yCol] = newY + ' mm';
  if (zCol >= 0) (rawValues[rowIndex] as unknown[])[zCol] = newZ + ' mm';

  return { success: true };
}

/**
 * Port of updatePlankDimensions — operates on in-memory data.
 */
export function updatePlankDimensionsInData(
  rawValues: unknown[][],
  rowIndex: number,
  newLenX: number,
  newLenY: number,
  newLenZ: number
): { success: boolean; error?: string } {
  if (!rawValues || rawValues.length === 0) {
    return { success: false, error: 'Data is empty' };
  }

  const headers = rawValues[0];
  const lowerHeaders = (headers as unknown[]).map((h) =>
    (h || '').toString().trim().toLowerCase()
  );

  const lenXCol = lowerHeaders.indexOf('lenx');
  const lenYCol = lowerHeaders.indexOf('leny');
  const lenZCol = lowerHeaders.indexOf('lenz');

  if (rowIndex < 1 || rowIndex >= rawValues.length) {
    return { success: false, error: 'Row index out of range' };
  }

  if (lenXCol >= 0) (rawValues[rowIndex] as unknown[])[lenXCol] = newLenX + ' mm';
  if (lenYCol >= 0) (rawValues[rowIndex] as unknown[])[lenYCol] = newLenY + ' mm';
  if (lenZCol >= 0) (rawValues[rowIndex] as unknown[])[lenZCol] = newLenZ + ' mm';

  return { success: true };
}

/**
 * Port of updateBoxPosition — updates all planks in a box.
 */
export function updateBoxPositionInData(
  rawValues: unknown[][],
  plankUpdates: { rowIndex: number; newX: number; newY: number; newZ: number }[]
): { success: boolean; updatedCount?: number; error?: string } {
  if (!rawValues || rawValues.length === 0) {
    return { success: false, error: 'Data is empty' };
  }

  const headers = rawValues[0];
  const lowerHeaders = (headers as unknown[]).map((h) =>
    (h || '').toString().trim().toLowerCase()
  );

  const xCol = lowerHeaders.indexOf('x');
  const yCol = lowerHeaders.indexOf('y');
  const zCol = lowerHeaders.indexOf('z');

  if (xCol < 0 || yCol < 0 || zCol < 0) {
    return { success: false, error: 'X, Y, or Z columns not found' };
  }

  let updatedCount = 0;
  for (const update of plankUpdates) {
    const { rowIndex, newX, newY, newZ } = update;
    if (rowIndex && rowIndex > 0 && rowIndex < rawValues.length) {
      (rawValues[rowIndex] as unknown[])[xCol] = Math.round(newX) + ' mm';
      (rawValues[rowIndex] as unknown[])[yCol] = Math.round(newY) + ' mm';
      (rawValues[rowIndex] as unknown[])[zCol] = Math.round(newZ) + ' mm';
      updatedCount++;
    }
  }

  return { success: true, updatedCount };
}
