/**
 * Visualiser Types
 * Backend-safe interfaces ported from frontend/src/types/visualiser/index.ts
 * (React/Three.js-specific types are excluded)
 */

// ============================================
// CORE GEOMETRY TYPES
// ============================================

export interface Position {
  x: number;
  y: number;
  z: number;
}

export interface Dimensions {
  lenX: number;
  lenY: number;
  lenZ: number;
}

// ============================================
// WALL / BOX / PLANK HIERARCHY
// ============================================

export interface Wall {
  id: string;
  entityName: string;
  roomName: string;
  unitLocation: string;
  position: Position;
  dimensions: Dimensions;
  boxes: Box[];
  rowIndex?: number;
}

export interface Box {
  id: string;
  entityName: string;
  roomName: string;
  unitLocation: string;
  boxModel: string;
  boxType: string;
  position: Position;
  dimensions: Dimensions;
  planks: Plank[];
  rowIndex?: number;
  boxWidth?: number;
  boxDepth?: number;
  boxHeight?: number;
  skirting?: number;
  skirtingWidth?: number;
  carcusThickness?: number;
  doorThickness?: number;
  backplankThickness?: number;
  carcusPly?: string;
  doorPly?: string;
  backPly?: string;
  rotZ?: number;
}

export interface Plank {
  id: string;
  entityName: string;
  material: string;
  materialColor: string;
  thickness: number;
  position: Position;
  dimensions: Dimensions;
  role: string;
  isDoor: boolean;
  assemblyOrder: number;
  autoGenerated: boolean;
  rowIndex?: number;
  operations?: PlankOperations;
}

// ============================================
// PLANK OPERATIONS
// ============================================

export interface PlankOperations {
  screws?: HoleOperation[];
  hinges?: HoleOperation[];
  holes?: HoleOperation[];
  vb_main?: HoleOperation[];
  vb_double?: HoleOperation[];
  slots?: GrooveOperation[];
  grooves?: GrooveOperation[];
  profiles?: GrooveOperation[];
  l_cuts?: LCutOperation[];
}

export interface HoleOperation {
  x: number;
  y: number;
  z: number;
  diameter?: number;
}

export interface GrooveOperation {
  x: number;
  y: number;
  z: number;
  length: number;
  width: number;
  depth: number;
  type?: 'slot' | 'groove' | 'profile';
}

export interface LCutOperation {
  start: Position;
  center: Position;
  end: Position;
  legacy?: boolean;
  x?: number;
  y?: number;
}

/** Row-shaped formatted plank (pipeline / DataTable) */
export interface FormattedPlankData {
  roomName: string;
  boxType: string;
  boxModel: string;
  boxOrientation: 'NS' | 'EW' | 'N/A';
  boxName: string;
  plankName: string;
  plankId: string;
  plankLength: number;
  plankWidth: number;
  plankThickness: number;
  plankMaterial: string;
  ebValue: number;
  ebApplied?: boolean;
  operations: PlankOperations;
  hardware?: Record<string, number>;
  notes?: string;
}

/** Aggregated material row for reports */
export interface MaterialSummary {
  materialThickness: string;
  baseMaterial: string;
  thickness: number;
  roomNames: string;
  plankCount: number;
  totalArea: number;
  sheetsUsed: number;
  avgAreaPerSheet: number;
  utilization: number;
  totalEdge: number;
}

// ============================================
// PIPELINE INPUT / OUTPUT
// ============================================

export interface EBSettings {
  [materialThickness: string]: number;
}

export interface CustomerDetails {
  customerName: string;
  firmName?: string;
  address?: string;
  phone?: string;
  email?: string;
  gst?: string;
  transportAmount?: number;
}

export interface NestingAlgorithmParams {
  algorithm: 'bfd' | 'ga' | 'sa' | 'pso' | 'tournament';
  populationSize?: number;
  generations?: number;
  mutationRate?: number;
  temperature?: number;
  coolingRate?: number;
  swarmSize?: number;
  iterations?: number;
}

export interface PipelineInput {
  rawValues: unknown[][];
  ebSettings: EBSettings;
  customerDetails?: CustomerDetails;
  hardwareData?: (string | number)[][];
  sftData?: (string | number)[][] | null;
  nestingParams?: NestingAlgorithmParams;
}

export interface PipelineResult {
  formattedData: unknown;
  plankList: unknown;
  cutlist: unknown;
  materialSummary: unknown;
  pressingList: unknown;
  materialEstimate: unknown;
  inputQA: unknown;
  outputQA: unknown;
  oversizedWarnings: string[];
  gcode?: unknown;
  winningConfigLabel?: string;
}

// ============================================
// NESTING CONSTANTS (shared with pipeline / nestingEngine)
// ============================================

export const SHEET_CONSTANTS = {
  SHEET_WIDTH: 1220,
  SHEET_HEIGHT: 2440,
  SPACING: 10,
  MARGIN: 10,
} as const;

// ============================================
// PLANK LIST
// ============================================

export interface PlankListItem {
  plankName: string;
  material: string;
  width: number;
  height: number;
  thickness: number;
  plankId: string;
  grain: 'Y' | 'N' | '';
  edgeBinding: number;
  sheetNumber?: number;
}

// ============================================
// NESTING
// ============================================

export interface NestResult {
  id: string;
  name: string;
  material: string;
  thickness: number;
  sheetNum: number;
  x: number;
  y: number;
  width: number;
  height: number;
  rotated: boolean;
  color: string;
  originalWidth: number;
  originalHeight: number;
  ebValue: number;
  holes: NestHole[];
}

export interface NestHole {
  x: number;
  y: number;
  type: string;
  isRectangular: boolean;
  description: string;
  diameter?: number;
  width?: number;
  length?: number;
}

// ============================================
// G-CODE
// ============================================

export interface GCodeResult {
  sheetName: string;
  fileName: string;
  materialFolder: string;
  thicknessFolder: string;
  content: string;
  plankCount: number;
}

export interface GCodeResponse {
  zipBase64: string;
  fileCount: number;
  fileNames: string[];
}

// ============================================
// CATALOG
// ============================================

export interface CatalogModel {
  id: string;
  entityName: string;
  level: number;
  material?: string;
  roomName?: string;
  unitLocation?: string;
  boxModel: string;
  boxType: string;
  lenX: number;
  lenY: number;
  lenZ: number;
  boxWidth: number;
  boxDepth: number;
  boxHeight: number;
  skirting: number;
  skirtingWidth: number;
  carcusThickness: number;
  doorThickness: number;
  backplankThickness: number;
  plankTemplates?: PlankTemplate[];
}

export interface PlankTemplate {
  entityName: string;
  material: string;
  level: number;
  rowIndex: number;
  lenX: number;
  lenY: number;
  lenZ: number;
  x: number;
  y: number;
  z: number;
  /** Level-3 features attached while parsing Google Sheets */
  subComponents?: unknown[];
}

/** Parsed catalog box with child planks (designer palette) */
export interface CatalogBoxWithPlanks extends CatalogModel {
  planks: PlankTemplate[];
}

export interface PlywoodOption {
  id: string;
  sno: string;
  brand: string;
  gradeType: string;
  material: string;
  thickness: number;
  price: number;
  remarks?: string;
  displayName: string;
}

export interface LaminateOption {
  id: string;
  sno: string;
  brand: string;
  code: string;
  colour: string;
  thickness: number;
  price: number;
  photoUrl?: string;
  comments?: string;
  displayName: string;
}

export interface CatalogData {
  models: CatalogModel[];
  plywoodOptions: PlywoodOption[];
  laminateOptions: LaminateOption[];
  /** Optional; required for 3D designer “add from catalog” */
  catalogBoxesWithPlanks?: CatalogBoxWithPlanks[];
  source: 'google-sheets' | 'csv';
}

// ============================================
// IMPORT
// ============================================

export interface ImportResult {
  rawValues: unknown[][];
  headers: string[];
  rowCount: number;
  validationErrors: string[];
  preview: unknown[][];
}
