/**
 * G-Code Generator
 * Generates CNC machine code for automated manufacturing
 * Ported from gcode.js
 */

import type {
  GCodeConfig,
  GCodePlank,
  GCodeResult,
  PlankOperations,
  HoleOperation,
  SlotOperation,
  LCutOperation,
} from "@/types/visualiser";

// ============================================
// Configuration
// ============================================

export const DEFAULT_CONFIG: GCodeConfig = {
  Z_SAFE: 5,
  SPINDLE_SPEED: 18000,
  CUTTING_FEED_RATE: 3000,
  PLUNGE_FEED_RATE: 1500,
  BIT_RADIUS: 3, // T1 = 6mm end mill
  TOOL_DIAMETER_T2: 4, // T2 = 4mm drill
};

// Tool definitions
const TOOLS = {
  T1: { diameter: 6, name: "6mm End Mill", type: "mill" },
  T2: { diameter: 4, name: "4mm Drill", type: "drill" },
  T3: { diameter: 5, name: "5mm Drill", type: "drill" },
  T4: { diameter: 8, name: "8mm Drill", type: "drill" },
  T5: { diameter: 35, name: "35mm Hinge Boring", type: "boring" },
  T6: { diameter: 20, name: "20mm VB Main", type: "boring" },
};

// ============================================
// Utility Functions
// ============================================

function formatNum(num: number): string {
  return num.toFixed(3);
}

function generateHeader(config: GCodeConfig, toolNumber: string): string[] {
  return [
    "; G-Code generated by Nestup Visualiser",
    `; Date: ${new Date().toISOString()}`,
    "",
    `G90 ; Absolute positioning`,
    `G21 ; Metric units (mm)`,
    `${toolNumber} ; Select tool`,
    `M3 S${config.SPINDLE_SPEED} ; Start spindle`,
    `G0 Z${config.Z_SAFE} ; Move to safe height`,
    "",
  ];
}

function generateFooter(config: GCodeConfig): string[] {
  return [
    "",
    `G0 Z${config.Z_SAFE} ; Return to safe height`,
    "M5 ; Stop spindle",
    "M30 ; End program",
    "",
  ];
}

// ============================================
// Profile Cutting (T1 - 6mm End Mill)
// ============================================

function generateProfileCut(
  plank: GCodePlank,
  config: GCodeConfig
): string[] {
  const lines: string[] = [];
  const { x, y, placedWidth, placedHeight, rotated } = plank;
  const bitRadius = config.BIT_RADIUS;

  // Calculate actual dimensions
  let width = placedWidth;
  let height = placedHeight;
  if (rotated) {
    [width, height] = [height, width];
  }

  // Profile cutting path (outside of part with tool offset)
  const startX = x - bitRadius;
  const startY = y - bitRadius;
  const endX = x + width + bitRadius;
  const endY = y + height + bitRadius;

  lines.push(`; Profile cut for ${plank.id}`);
  lines.push(`G0 Z${config.Z_SAFE}`);
  lines.push(`G0 X${formatNum(startX)} Y${formatNum(startY)}`);
  lines.push(`G1 Z-18 F${config.PLUNGE_FEED_RATE} ; Cut depth (18mm)`);
  
  // Clockwise profile
  lines.push(`G1 X${formatNum(endX)} F${config.CUTTING_FEED_RATE}`);
  lines.push(`G1 Y${formatNum(endY)}`);
  lines.push(`G1 X${formatNum(startX)}`);
  lines.push(`G1 Y${formatNum(startY)}`);
  
  lines.push(`G0 Z${config.Z_SAFE}`);
  lines.push("");

  return lines;
}

// ============================================
// L-Cuts (Corner notches)
// ============================================

function generateLCuts(
  plank: GCodePlank,
  lCuts: LCutOperation[],
  config: GCodeConfig
): string[] {
  const lines: string[] = [];
  
  if (!lCuts || lCuts.length === 0) return lines;

  const { x, y, placedWidth, placedHeight, rotated } = plank;
  let width = placedWidth;
  let height = placedHeight;
  if (rotated) {
    [width, height] = [height, width];
  }

  lines.push(`; L-Cuts for ${plank.id}`);

  for (const cut of lCuts) {
    // Transform coordinates based on rotation
    let cutX = cut.x;
    let cutY = cut.y;
    if (rotated) {
      [cutX, cutY] = [cutY, height - cutX];
    }

    const absX = x + cutX;
    const absY = y + cutY;

    // L-cut is typically a corner cut
    // Cut an L-shape from the corner
    const lSize = 50; // L-cut size
    const bitRadius = config.BIT_RADIUS;

    lines.push(`G0 Z${config.Z_SAFE}`);
    lines.push(`G0 X${formatNum(absX - bitRadius)} Y${formatNum(absY)}`);
    lines.push(`G1 Z-18 F${config.PLUNGE_FEED_RATE}`);
    lines.push(`G1 X${formatNum(absX + lSize)} F${config.CUTTING_FEED_RATE}`);
    lines.push(`G1 Y${formatNum(absY + lSize)}`);
    lines.push(`G1 X${formatNum(absX)}`);
    lines.push(`G0 Z${config.Z_SAFE}`);
    lines.push("");
  }

  return lines;
}

// ============================================
// Slots / Grooves (T1 - End Mill)
// ============================================

function generateSlots(
  plank: GCodePlank,
  slots: SlotOperation[],
  config: GCodeConfig
): string[] {
  const lines: string[] = [];
  
  if (!slots || slots.length === 0) return lines;

  const { x, y, placedWidth, placedHeight, rotated } = plank;

  lines.push(`; Slots/Grooves for ${plank.id}`);

  for (const slot of slots) {
    // Transform coordinates
    let slotX = slot.x;
    let slotY = slot.y;
    let slotLength = slot.length;
    let slotWidth = slot.width;
    
    if (rotated) {
      [slotX, slotY] = [slotY, placedHeight - slotX - slotWidth];
      [slotLength, slotWidth] = [slotWidth, slotLength];
    }

    const absX = x + slotX;
    const absY = y + slotY;
    const depth = slot.depth || 8;
    const bitRadius = config.BIT_RADIUS;

    // Multiple passes for deep grooves
    const passDepth = 4;
    const numPasses = Math.ceil(depth / passDepth);

    for (let pass = 1; pass <= numPasses; pass++) {
      const currentDepth = Math.min(pass * passDepth, depth);
      
      lines.push(`; Pass ${pass}/${numPasses}`);
      lines.push(`G0 Z${config.Z_SAFE}`);
      lines.push(`G0 X${formatNum(absX + bitRadius)} Y${formatNum(absY + slotWidth / 2)}`);
      lines.push(`G1 Z${formatNum(-currentDepth)} F${config.PLUNGE_FEED_RATE}`);
      lines.push(`G1 X${formatNum(absX + slotLength - bitRadius)} F${config.CUTTING_FEED_RATE}`);
    }
    
    lines.push(`G0 Z${config.Z_SAFE}`);
    lines.push("");
  }

  return lines;
}

// ============================================
// Drilling Operations (T2-T6)
// ============================================

function generateDrillHoles(
  plank: GCodePlank,
  holes: HoleOperation[],
  toolNum: string,
  holeType: string,
  config: GCodeConfig
): string[] {
  const lines: string[] = [];
  
  if (!holes || holes.length === 0) return lines;

  const { x, y, placedWidth, placedHeight, rotated } = plank;

  lines.push(`; ${holeType} holes for ${plank.id} (${toolNum})`);

  for (const hole of holes) {
    // Transform coordinates
    let holeX = hole.x;
    let holeY = hole.y;
    
    if (rotated) {
      [holeX, holeY] = [holeY, placedHeight - holeX];
    }

    const absX = x + holeX;
    const absY = y + holeY;
    const depth = hole.z || 12;

    lines.push(`G0 Z${config.Z_SAFE}`);
    lines.push(`G0 X${formatNum(absX)} Y${formatNum(absY)}`);
    lines.push(`G1 Z${formatNum(-depth)} F${config.PLUNGE_FEED_RATE}`);
    lines.push(`G0 Z${config.Z_SAFE}`);
  }

  lines.push("");
  return lines;
}

// ============================================
// Hinge Boring (T5 - 35mm)
// ============================================

function generateHingeBoring(
  plank: GCodePlank,
  hinges: HoleOperation[],
  config: GCodeConfig
): string[] {
  const lines: string[] = [];
  
  if (!hinges || hinges.length === 0) return lines;

  const { x, y, placedWidth, placedHeight, rotated } = plank;

  lines.push(`; Hinge boring for ${plank.id} (T5)`);

  for (const hinge of hinges) {
    let hingeX = hinge.x;
    let hingeY = hinge.y;
    
    if (rotated) {
      [hingeX, hingeY] = [hingeY, placedHeight - hingeX];
    }

    const absX = x + hingeX;
    const absY = y + hingeY;
    const depth = hinge.z || 12;

    // Hinge boring uses pecking cycle for better chip evacuation
    lines.push(`G0 Z${config.Z_SAFE}`);
    lines.push(`G0 X${formatNum(absX)} Y${formatNum(absY)}`);
    lines.push(`G83 X${formatNum(absX)} Y${formatNum(absY)} Z${formatNum(-depth)} R1 Q3 F${config.PLUNGE_FEED_RATE} ; Peck drill`);
    lines.push(`G80 ; Cancel canned cycle`);
  }

  lines.push(`G0 Z${config.Z_SAFE}`);
  lines.push("");
  return lines;
}

// ============================================
// VB (Connecting bolt) holes
// ============================================

function generateVBHoles(
  plank: GCodePlank,
  vbMain: HoleOperation[],
  vbDouble: HoleOperation[],
  config: GCodeConfig
): string[] {
  const lines: string[] = [];

  // VB Main (20mm, T6)
  if (vbMain && vbMain.length > 0) {
    const { x, y, placedHeight, rotated } = plank;
    lines.push(`; VB Main holes for ${plank.id} (T6 - 20mm)`);

    for (const vb of vbMain) {
      let vbX = vb.x;
      let vbY = vb.y;
      
      if (rotated) {
        [vbX, vbY] = [vbY, placedHeight - vbX];
      }

      const absX = x + vbX;
      const absY = y + vbY;
      const depth = vb.z || 13;

      lines.push(`G0 Z${config.Z_SAFE}`);
      lines.push(`G0 X${formatNum(absX)} Y${formatNum(absY)}`);
      lines.push(`G1 Z${formatNum(-depth)} F${config.PLUNGE_FEED_RATE}`);
      lines.push(`G0 Z${config.Z_SAFE}`);
    }
    lines.push("");
  }

  // VB Double (5mm, T3)
  if (vbDouble && vbDouble.length > 0) {
    lines.push(...generateDrillHoles(plank, vbDouble, "T3", "VB Double", config));
  }

  return lines;
}

// ============================================
// Main G-Code Generation
// ============================================

function generateGCodeForPlank(
  plank: GCodePlank,
  config: GCodeConfig = DEFAULT_CONFIG
): Map<string, string[]> {
  const toolCodes = new Map<string, string[]>();
  const features = plank.features || {};

  // T1 operations (profile, slots, L-cuts)
  const t1Lines: string[] = [];
  t1Lines.push(...generateProfileCut(plank, config));
  if (features.slots) {
    t1Lines.push(...generateSlots(plank, features.slots, config));
  }
  if (features.l_cuts) {
    t1Lines.push(...generateLCuts(plank, features.l_cuts, config));
  }
  if (t1Lines.length > 0) {
    toolCodes.set("T1", t1Lines);
  }

  // T2 operations (4mm screw holes)
  if (features.screws && features.screws.length > 0) {
    const t2Lines = generateDrillHoles(plank, features.screws, "T2", "Screw", config);
    toolCodes.set("T2", t2Lines);
  }

  // T5 operations (35mm hinge boring)
  if (features.hinges && features.hinges.length > 0) {
    const t5Lines = generateHingeBoring(plank, features.hinges, config);
    toolCodes.set("T5", t5Lines);
  }

  // T6 and T3 operations (VB holes)
  if (features.vb_main || features.vb_double) {
    const vbLines = generateVBHoles(plank, features.vb_main || [], features.vb_double || [], config);
    if (vbLines.length > 0) {
      toolCodes.set("T6", vbLines);
    }
  }

  return toolCodes;
}

// ============================================
// Sheet-level G-Code Generation
// ============================================

export interface GenerateGCodeOptions {
  config?: GCodeConfig;
  organizeBySuperCategory?: boolean;
}

export function generateGCodeForSheet(
  planks: GCodePlank[],
  sheetName: string,
  options: GenerateGCodeOptions = {}
): GCodeResult[] {
  const config = options.config || DEFAULT_CONFIG;
  const results: GCodeResult[] = [];

  // Group operations by tool
  const toolOperations = new Map<string, string[]>();

  for (const plank of planks) {
    const plankCodes = generateGCodeForPlank(plank, config);
    
    plankCodes.forEach((lines, tool) => {
      const existing = toolOperations.get(tool) || [];
      existing.push(`; Plank: ${plank.id} - ${plank.name}`);
      existing.push(...lines);
      toolOperations.set(tool, existing);
    });
  }

  // Generate files per tool
  toolOperations.forEach((operations, tool) => {
    const toolInfo = TOOLS[tool as keyof typeof TOOLS];
    const fileName = `${sheetName}_${tool}_${toolInfo?.name.replace(/\s+/g, "_") || "unknown"}.nc`;
    
    const content = [
      ...generateHeader(config, tool),
      `; Sheet: ${sheetName}`,
      `; Tool: ${tool} - ${toolInfo?.name || "Unknown"}`,
      `; Total planks: ${planks.length}`,
      "",
      ...operations,
      ...generateFooter(config),
    ].join("\n");

    results.push({
      sheetName,
      fileName,
      materialFolder: planks[0]?.material || "unknown",
      thicknessFolder: `${planks[0]?.thickness || 0}mm`,
      content,
      plankCount: planks.length,
    });
  });

  return results;
}

// ============================================
// Full Project G-Code Generation
// ============================================

export interface ProjectGCodeResult {
  files: GCodeResult[];
  totalFiles: number;
  totalPlanks: number;
  byMaterial: Record<string, number>;
}

export function generateGCodeForProject(
  planksBySheet: Record<string, GCodePlank[]>,
  options: GenerateGCodeOptions = {}
): ProjectGCodeResult {
  const allFiles: GCodeResult[] = [];
  let totalPlanks = 0;
  const byMaterial: Record<string, number> = {};

  for (const [sheetName, planks] of Object.entries(planksBySheet)) {
    const sheetResults = generateGCodeForSheet(planks, sheetName, options);
    allFiles.push(...sheetResults);
    
    totalPlanks += planks.length;
    for (const plank of planks) {
      const key = `${plank.material}_${plank.thickness}mm`;
      byMaterial[key] = (byMaterial[key] || 0) + 1;
    }
  }

  return {
    files: allFiles,
    totalFiles: allFiles.length,
    totalPlanks,
    byMaterial,
  };
}

// ============================================
// ZIP Generation Helper
// ============================================

export async function generateGCodeZip(
  results: ProjectGCodeResult,
  projectName: string
): Promise<Blob> {
  const { default: JSZip } = await import("jszip");
  const zip = new JSZip();

  // Organize by material/thickness
  for (const file of results.files) {
    const folderPath = `${projectName}/${file.materialFolder}/${file.thicknessFolder}`;
    zip.file(`${folderPath}/${file.fileName}`, file.content);
  }

  // Add summary file
  const summary = [
    `G-Code Generation Summary`,
    `========================`,
    `Project: ${projectName}`,
    `Generated: ${new Date().toISOString()}`,
    ``,
    `Total Files: ${results.totalFiles}`,
    `Total Planks: ${results.totalPlanks}`,
    ``,
    `Materials:`,
    ...Object.entries(results.byMaterial).map(([mat, count]) => `  - ${mat}: ${count} planks`),
  ].join("\n");

  zip.file(`${projectName}/summary.txt`, summary);

  return await zip.generateAsync({ type: "blob" });
}

const gcodeExports = {
  generateGCodeForSheet,
  generateGCodeForProject,
  generateGCodeZip,
  DEFAULT_CONFIG,
};

export default gcodeExports;
