import { CutList, CutOperation, GCodeCommand, GCodeProgram } from '../types/bim.types';

// CNC machine parameters
const CNC_PARAMS = {
  rapidMoveSpeed: 5000, // mm/min
  cutSpeed: 1000, // mm/min
  plungeSpeed: 500, // mm/min
  cutDepth: 18, // mm (should match material thickness)
  safeHeight: 10, // mm above material for rapid moves
  toolDiameter: 6, // mm
  spindleSpeed: 18000, // RPM
};

/**
 * @description Generates G-code from a cutlist
 * @param cutList The cutlist to generate G-code from
 * @returns A G-code program
 */
export function generateGCode(cutList: CutList): GCodeProgram {
  // Validate input
  if (!cutList || !cutList.sheets || cutList.sheets.length === 0) {
    throw new Error('Invalid cutlist provided for G-code generation');
  }

  const commands: GCodeCommand[] = [];
  let totalCuts = 0;

  // Add program header
  addProgramHeader(commands);

  // Process each sheet
  cutList.sheets.forEach((sheet, sheetIndex) => {
    // Add sheet header comment
    commands.push({
      code: '',
      params: {},
      comment: `Sheet ${sheetIndex + 1}: ${sheet.sheetId} (${sheet.materialCode})`
    });

    // Add tool setup for this sheet
    addToolSetup(commands, sheet.materialCode);

    // Process each cut on this sheet
    sheet.cuts.forEach((cut, cutIndex) => {
      // Add cut header comment
      commands.push({
        code: '',
        params: {},
        comment: `Cut ${cutIndex + 1}: ${cut.plankId} (${cut.width}x${cut.height}mm)`
      });

      // Generate G-code for this cut
      addCutOperations(commands, cut, CNC_PARAMS);

      totalCuts++;
    });

    // Return to safe position after processing the sheet
    commands.push({
      code: 'G0',
      params: { Z: CNC_PARAMS.safeHeight },
      comment: 'Raise to safe height'
    });

    commands.push({
      code: 'G0',
      params: { X: 0, Y: 0 },
      comment: 'Return to origin'
    });

    // Add sheet footer comment
    commands.push({
      code: '',
      params: {},
      comment: `End of sheet ${sheetIndex + 1}`
    });
  });

  // Add program footer
  addProgramFooter(commands);

  return {
    commands,
    metadata: {
      generatedAt: new Date().toISOString(),
      materialCode: cutList.sheets.length > 0 ? cutList.sheets[0].materialCode : 'unknown',
      totalCuts
    }
  };
}

/**
 * @description Adds program header commands
 * @param commands The array of G-code commands to add to
 */
function addProgramHeader(commands: GCodeCommand[]): void {
  commands.push(
    {
      code: '',
      params: {},
      comment: 'Program generated by Nestup BIM'
    },
    {
      code: '',
      params: {},
      comment: `Generated on ${new Date().toLocaleString()}`
    },
    {
      code: 'G21',
      params: {},
      comment: 'Set units to millimeters'
    },
    {
      code: 'G90',
      params: {},
      comment: 'Use absolute coordinates'
    },
    {
      code: 'G17',
      params: {},
      comment: 'Select XY plane'
    },
    {
      code: 'G54',
      params: {},
      comment: 'Use work coordinate system 1'
    },
    {
      code: 'G0',
      params: { Z: CNC_PARAMS.safeHeight },
      comment: 'Move to safe height'
    },
    {
      code: 'G0',
      params: { X: 0, Y: 0 },
      comment: 'Move to origin'
    }
  );
}

/**
 * @description Adds tool setup commands for a specific material
 * @param commands The array of G-code commands to add to
 * @param materialCode The material code
 */
function addToolSetup(commands: GCodeCommand[], materialCode: string): void {
  // In a real implementation, tool selection might depend on the material
  commands.push(
    {
      code: '',
      params: {},
      comment: `Tool setup for material: ${materialCode}`
    },
    {
      code: 'M6',
      params: { T: 1 },
      comment: 'Select tool 1 (end mill)'
    },
    {
      code: 'M3',
      params: { S: CNC_PARAMS.spindleSpeed },
      comment: 'Start spindle clockwise'
    },
    {
      code: 'G0',
      params: { Z: CNC_PARAMS.safeHeight },
      comment: 'Move to safe height'
    }
  );
}

/**
 * @description Adds G-code commands for a specific cut operation
 * @param commands The array of G-code commands to add to
 * @param cut The cut operation
 * @param params CNC machine parameters
 */
function addCutOperations(
  commands: GCodeCommand[],
  cut: CutOperation,
  params: typeof CNC_PARAMS
): void {
  // Calculate cut dimensions based on rotation
  const width = cut.rotation ? cut.height : cut.width;
  const height = cut.rotation ? cut.width : cut.height;

  // Calculate corner positions
  const x1 = cut.position.x;
  const y1 = cut.position.y;
  const x2 = x1 + width;
  const y2 = y1 + height;

  // Adjust for tool diameter (offset inward by half tool diameter)
  const offset = params.toolDiameter / 2;
  const xMin = x1 + offset;
  const yMin = y1 + offset;
  const xMax = x2 - offset;
  const yMax = y2 - offset;

  // Move to start position
  commands.push(
    {
      code: 'G0',
      params: { X: xMin, Y: yMin },
      comment: 'Move to start position'
    },
    {
      code: 'G0',
      params: { Z: params.safeHeight },
      comment: 'Move to safe height'
    }
  );

  // Plunge to cutting depth
  commands.push(
    {
      code: 'G1',
      params: { Z: -params.cutDepth, F: params.plungeSpeed },
      comment: 'Plunge to cutting depth'
    }
  );

  // Cut rectangle (counterclockwise to conventional cut)
  commands.push(
    {
      code: 'G1',
      params: { X: xMax, F: params.cutSpeed },
      comment: 'Cut bottom edge'
    },
    {
      code: 'G1',
      params: { Y: yMax },
      comment: 'Cut right edge'
    },
    {
      code: 'G1',
      params: { X: xMin },
      comment: 'Cut top edge'
    },
    {
      code: 'G1',
      params: { Y: yMin },
      comment: 'Cut left edge'
    }
  );

  // Return to safe height
  commands.push(
    {
      code: 'G0',
      params: { Z: params.safeHeight },
      comment: 'Return to safe height'
    }
  );
}

/**
 * @description Adds program footer commands
 * @param commands The array of G-code commands to add to
 */
function addProgramFooter(commands: GCodeCommand[]): void {
  commands.push(
    {
      code: 'M5',
      params: {},
      comment: 'Stop spindle'
    },
    {
      code: 'G0',
      params: { Z: CNC_PARAMS.safeHeight },
      comment: 'Move to safe height'
    },
    {
      code: 'G0',
      params: { X: 0, Y: 0 },
      comment: 'Return to origin'
    },
    {
      code: 'M30',
      params: {},
      comment: 'End program and rewind'
    }
  );
}

/**
 * @description Formats a G-code program as a string
 * @param program The G-code program to format
 * @returns A string representation of the G-code program
 */
export function formatGCodeAsString(program: GCodeProgram): string {
  let gcode = '';

  program.commands.forEach(command => {
    if (command.code) {
      // Format the command code and parameters
      let line = command.code;

      Object.entries(command.params).forEach(([key, value]) => {
        line += ` ${key}${value}`;
      });

      // Add comment if present
      if (command.comment) {
        line += ` ; ${command.comment}`;
      }

      gcode += line + '\n';
    } else if (command.comment) {
      // Comment-only line
      gcode += `; ${command.comment}\n`;
    } else {
      // Empty line
      gcode += '\n';
    }
  });

  return gcode;
}
