/**
 * Visualiser Types
 * TypeScript interfaces matching the Apps Script data structure
 */

// ============================================
// CORE GEOMETRY TYPES
// ============================================

export interface Position {
  x: number;
  y: number;
  z: number;
}

export interface Dimensions {
  lenX: number;
  lenY: number;
  lenZ: number;
}

export interface Vector3 {
  x: number;
  y: number;
  z: number;
}

// ============================================
// WALL / BOX / PLANK HIERARCHY
// ============================================

/** Wall feature from ArUco/measurement (switchboard, window, door) for 3D placement */
export interface WallFeature {
  type: string;
  x_mm?: number;
  y_mm?: number;
  width_mm?: number;
  height_mm?: number;
}

export interface Wall {
  id: string;
  entityName: string;
  roomName: string;
  unitLocation: string; // 'North', 'South', 'East', 'West'
  position: Position;
  dimensions: Dimensions;
  boxes: Box[];
  /** Detected features (switchboards, windows, doors) with mm coordinates from measurement */
  wallFeatures?: WallFeature[];
  rowIndex?: number;
}

export interface Box {
  id: string;
  entityName: string;
  roomName: string;
  unitLocation: string;
  boxModel: string;
  boxType: string;
  position: Position;
  dimensions: Dimensions;
  planks: Plank[];
  checklist: ChecklistItem[];
  rowIndex?: number;
  // Editable options from catalog
  boxWidth?: number;
  boxDepth?: number;
  boxHeight?: number;
  skirting?: number;
  skirtingWidth?: number;
  carcusThickness?: number;
  doorThickness?: number;
  backplankThickness?: number;
  carcusPly?: string;
  doorPly?: string;
  backPly?: string;
  rotZ?: number;
  // Laminate selections
  outerLaminate?: LaminateOption;
  innerLaminate?: LaminateOption;
}

export interface Plank {
  id: string;
  entityName: string;
  material: string;
  materialColor: string;
  thickness: number;
  position: Position;
  dimensions: Dimensions;
  role: PlankRole;
  explodeDirection: Vector3;
  assemblyDirection: AssemblyDirection;
  isDoor: boolean;
  hingeSide?: 'left' | 'right';
  assemblyOrder: number;
  stepNumber?: number;
  autoGenerated: boolean;
  rowIndex?: number;
  // Operations (holes, grooves, etc.)
  operations?: PlankOperations;
  // Laminate info
  outerLaminate?: string;
  innerLaminate?: string;
  // Laminate texture URLs for 3D visualization
  outerLaminateUrl?: string;
  innerLaminateUrl?: string;
  laminateCode?: string;
  laminateBrand?: string;
  // Computed texture URL (used by renderer)
  textureUrl?: string;
}

export type PlankRole = 
  | 'left' | 'right' | 'top' | 'bottom' 
  | 'back' | 'front' | 'door' | 'shelf' 
  | 'skirting' | 'facia' | 'drawer' | 'dummy' | 'other';

export interface AssemblyDirection {
  arrow: string;
  text: string;
}

export interface ChecklistItem {
  id: string;
  name: string;
  material: string;
  dimensions: string;
  checked?: boolean;
}

// ============================================
// PLANK OPERATIONS (HOLES, GROOVES, ETC.)
// ============================================

export interface PlankOperations {
  screws?: HoleOperation[];
  hinges?: HoleOperation[];
  holes?: HoleOperation[];
  vb_main?: HoleOperation[];
  vb_double?: HoleOperation[];
  slots?: GrooveOperation[];
  grooves?: GrooveOperation[];
  profiles?: GrooveOperation[];
  l_cuts?: LCutOperation[];
}

export interface HoleOperation {
  x: number;
  y: number;
  z: number;
  diameter?: number;
}

export interface GrooveOperation {
  x: number;
  y: number;
  z: number;
  length: number;
  width: number;
  depth: number;
  type?: 'slot' | 'groove' | 'profile';
}

export interface LCutOperation {
  start: Position;
  center: Position;
  end: Position;
  legacy?: boolean;
  x?: number;
  y?: number;
}

// ============================================
// CATALOG MODELS
// ============================================

export interface CatalogModel {
  id: string;
  entityName: string;
  level: number;
  material?: string;
  roomName?: string;
  unitLocation?: string;
  boxModel: string;
  boxType: string;
  // Default dimensions
  lenX: number;
  lenY: number;
  lenZ: number;
  // Box parameters
  boxWidth: number;
  boxDepth: number;
  boxHeight: number;
  skirting: number;
  skirtingWidth: number;
  carcusThickness: number;
  doorThickness: number;
  backplankThickness: number;
  // Plank templates (actual plank data from catalog)
  plankTemplates?: PlankTemplate[];
}

export interface PlankTemplate {
  entityName: string;
  material: string;
  level: number;
  rowIndex: number;
  // Actual dimensions from catalog (in mm)
  lenX: number;  // width
  lenY: number;  // depth
  lenZ: number;  // height
  // Actual position from catalog (in mm, relative to box origin)
  x: number;
  y: number;
  z: number;
  // Sub-components (level 3 items like holes, grooves)
  subComponents?: SubComponentTemplate[];
}

export interface SubComponentTemplate {
  entityName: string;
  level: number;
  lenX: number;
  lenY: number;
  lenZ: number;
  x: number;
  y: number;
  z: number;
  rowIndex: number;
}

// ============================================
// MATERIAL LIBRARY
// ============================================

export interface PlywoodOption {
  id: string;
  sno: string;
  brand: string;
  gradeType: string;
  material: string; // 'Plywood', 'MDF', 'HDHMR', 'BB'
  thickness: number;
  price: number;
  remarks?: string;
  displayName: string; // e.g., "Century MR Plywood 18mm"
}

export interface LaminateOption {
  id: string;
  sno: string;
  brand: string;
  code: string;
  colour: string;
  thickness: number;
  price: number;
  photoUrl?: string;
  comments?: string;
  displayName: string; // e.g., "Century 5836 SL"
}

export interface EdgebandOption {
  id: string;
  brand: string;
  code: string;
  colour: string;
  width: number;
  thickness: number;
  price: number;
}

// ============================================
// FORMATTED DATA (OUTPUT OF FORMATTER)
// ============================================

export interface FormattedPlankData {
  roomName: string;
  boxType: string;
  boxModel: string;
  boxOrientation: 'NS' | 'EW' | 'N/A';
  boxName: string;
  plankName: string;
  plankId: string;
  plankLength: number;
  plankWidth: number;
  plankThickness: number;
  plankMaterial: string;
  ebValue: number;
  ebApplied?: boolean;
  // Dynamic operation columns
  operations: PlankOperations;
  // Hardware quantities
  hardware?: Record<string, number>;
  notes?: string;
}

// ============================================
// PLANK LIST
// ============================================

export interface PlankListItem {
  plankName: string;
  material: string;
  width: number;
  height: number;
  thickness: number;
  plankId: string;
  grain: 'Y' | 'N' | '';
  edgeBinding: number; // in meters
  /** Set when planks are assigned to sheets (e.g. after nesting). */
  sheetNumber?: number;
}

// ============================================
// NESTING / CUTLIST
// ============================================

export interface NestResult {
  id: string;
  name: string;
  material: string;
  thickness: number;
  sheetNum: number;
  x: number;
  y: number;
  width: number;
  height: number;
  rotated: boolean;
  color: string;
  // Original dimensions (before EB subtraction)
  originalWidth: number;
  originalHeight: number;
  ebValue: number;
  // Operations for CNC
  holes: NestHole[];
}

export interface NestHole {
  x: number;
  y: number;
  type: string;
  isRectangular: boolean;
  description: string;
  diameter?: number;
  width?: number;
  length?: number;
}

export interface SheetLayout {
  sheetNum: number;
  materialThickness: string;
  planks: NestResult[];
  utilization: number;
  freeRects: FreeRect[];
}

export interface FreeRect {
  x: number;
  y: number;
  width: number;
  height: number;
}

// ============================================
// REPORTS
// ============================================

export interface MaterialSummary {
  materialThickness: string;
  baseMaterial: string;
  thickness: number;
  roomNames: string;
  plankCount: number;
  totalArea: number;
  sheetsUsed: number;
  avgAreaPerSheet: number;
  utilization: number;
  totalEdge: number;
}

export interface MaterialEstimate {
  plywoods: PlywoodEstimate[];
  laminates: LaminateEstimate[];
  edgeBandings: EdgeBandingEstimate[];
  hardware: HardwareEstimate[];
  totalSqFt: number;
}

export interface PlywoodEstimate {
  description: string;
  thickness: string;
  quantity: number;
  unit: string;
}

export interface LaminateEstimate {
  description: string;
  brandColourCode: string;
  quantity: number;
  unit: string;
}

export interface EdgeBandingEstimate {
  description: string;
  brandColourCode: string;
  widthThickness: string;
  quantity: number;
  unit: string;
}

export interface HardwareEstimate {
  description: string;
  quantity: number;
  unit: string;
}

export interface QASheetItem {
  id: string;
  description: string;
  brandColourCode?: string;
  thickness?: string;
  width?: number;
  height?: number;
  count?: number;
  checked: boolean;
  comments: string;
}

export interface PressingListItem {
  sno: number;
  material: string;
  plyType: string;
  thickness: string;
  sheetQuantity: number;
  pressingCompleted: boolean;
  comments: string;
}

export interface SFTResult {
  boxModel: string;
  boxType: string;
  orientation: string;
  lengthMM: number;
  widthMM: number;
  squareFeet: number;
  originalRow: number;
}

// ============================================
// DESIGN STATE
// ============================================

/** Installation guide / room viewer edit mode */
export type EditMode = 'view' | 'select' | 'place' | 'move' | 'rotate' | 'boxMove';

export type DesignMode = 'select' | 'place' | 'move' | 'rotate' | 'paint' | 'guidelines' | 'measure';

// ============================================
// MEASUREMENT TOOL TYPES
// ============================================

export type MeasurementMode = 'measure' | 'guide_create';

export interface MeasurementResult {
  id: string;
  distance: number;
  deltaX: number;
  deltaY: number;
  deltaZ: number;
  startPoint: Position;
  endPoint: Position;
  timestamp: number;
}

export interface MeasureGuideLine {
  id: string;
  origin: Position;
  direction: Position;
  type: 'parallel' | 'perpendicular' | 'axis_x' | 'axis_y' | 'axis_z' | 'point_to_point';
  offset: number;
  referenceEdgeId?: string;
  visible: boolean;
  color: string;
}

export interface MeasureGuidePoint {
  id: string;
  position: Position;
  type: 'endpoint' | 'midpoint' | 'custom';
  label?: string;
}

export interface HoverMeasurementInfo {
  type: 'edge' | 'face';
  position: Position;
  screenPosition: { x: number; y: number };
  length?: number;
  area?: number;
  boxId: string;
  edgeIndex?: number;
}

export interface BoxEdge {
  id: string;
  boxId: string;
  start: Position;
  end: Position;
  direction: Position;
  length: number;
  edgeIndex: number;
}

// ============================================
// GUIDELINES (Construction Lines)
// ============================================

export interface Guideline {
  id: string;
  start: Position;
  end: Position;
  axis: 'x' | 'y' | 'z';
  color: string;
  isTemporary: boolean;
  label?: string;
}

export interface DesignData {
  walls: Wall[];
  materialLegend: MaterialLegendItem[];
  summary: DesignSummary;
}

export interface MaterialLegendItem {
  name: string;
  color: string;
}

export interface DesignSummary {
  totalWalls: number;
  totalBoxes: number;
  totalPlanks: number;
  timestamp?: string;
  autoGeneratedIds?: number;
}

// ============================================
// FILE GENERATION PROGRESS
// ============================================

export type GenerationStepStatus = 'pending' | 'processing' | 'complete' | 'error';

export interface GenerationStep {
  id: string;
  name: string;
  status: GenerationStepStatus;
  progress?: number;
  error?: string;
  result?: unknown;
}

export interface GenerationProgress {
  steps: GenerationStep[];
  currentStepId: string | null;
  isComplete: boolean;
  hasError: boolean;
}

// ============================================
// CONSTANTS
// ============================================

export const SHEET_CONSTANTS = {
  SHEET_WIDTH: 1220,
  SHEET_HEIGHT: 2440,
  SPACING: 10,
  MARGIN: 10,
} as const;

export const MATERIAL_THICKNESS = {
  expose: 18,
  inner: 18,
  back: 6,
} as const;

export const EDGE_BANDING = {
  INNER_EDGEBANDING: 1,
  COLOR_EDGEBANDING: 2,
} as const;

// ============================================
// DESIGNER CONFIG (matches Apps Script)
// ============================================

export interface DesignerConfig {
  catalogueFileId?: string;
  catalogueSheetName: string;
  materialCatalogFileId?: string;
  materialSheets: {
    plywood: string;
    laminate: string;
    edgeband: string;
    hardware: string;
  };
  sheets: {
    siteMeasurements: string;
    designData: string;
  };
  catalogueColumns: Record<string, number>;
  plywoodColumns: Record<string, number>;
  laminateColumns: Record<string, number>;
  coreMaterials: Record<string, string>;
  wallLayout: {
    spacing: number;
    floorExtension: number;
    defaultFloorY: number;
    colors: string[];
    activeHighlight: string;
    labelHeight: number;
  };
  editableOptions: EditableOption[];
}

export interface EditableOption {
  key: string;
  header: string;
  label: string;
  unit?: string;
  type: 'number' | 'material-dropdown' | 'readonly';
  category?: 'plywood';
  thicknessTarget?: string;
  derivedFrom?: string;
}

// ============================================
// STORE DATA TYPES
// ============================================

/** Cutlist visualization data (sheets with nested planks) */
export interface CutlistData {
  sheets: SheetLayout[];
  summary: {
    totalPlanks: number;
    totalSheets: number;
    avgUtilization: number;
  };
  [key: string]: unknown;
}

/** Installation guide data (walls → boxes → planks with step ordering) */
export interface InstallationGuideData {
  walls: Wall[];
  materialLegend: MaterialLegendItem[];
  [key: string]: unknown;
}

/** Single G-code result file entry (used by store) */
export interface GCodeResult {
  sheetName: string;
  fileName: string;
  materialFolder: string;
  thicknessFolder: string;
  content: string;
  plankCount: number;
}

/** Designer state snapshot (used by store) */
export interface DesignerState {
  walls: Wall[];
  selectedWallId?: string | null;
  selectedBoxId?: string | null;
  selectedPlankId?: string | null;
  [key: string]: unknown;
}
