import { Ruler, ClipboardList, Package, FileText, CreditCard, CheckSquare, Calculator, Factory, PackageOpen, Truck, Wrench } from "lucide-react"

export const processSteps = [
  {
    id: "measure",
    icon: Ruler,
    imgSrc: "/img/measure.png",
    imgAlt: "laser measurement tools",
    title: "Site Measurements",
    shortDescription: "Professional measurement team visits your location using advanced laser tools to capture precise, millimeter-accurate dimensions.",
    details: {
      overview: "Our site measurement team conducts thorough on-site assessments to capture accurate, millimeter-precise measurements that form the foundation for all subsequent design and production stages.",
      keyActivities: [
        "Comprehensive measurement of heights, widths, and depths using laser measurement tools",
        "Documentation of electrical switchboard positions, windows, doors, beams, and columns",
        "Recording of surface undulations and structural anomalies",
        "Collection of project-level inputs including client details and basic project information",
      ],
      technicalSpecs: [
        "Material ID configuration with  thickness, laminate codes, and edge banding specifications",
        "Grain direction mapping for specific planks",
        "Overall material thickness calculations (Outer Laminate + Plywood Thickness + Inner Laminate)",
        "Establishment of material codes that remain consistent throughout the project",
      ],
      deliverables: [
        "Detailed site measurement report with mm-level accuracy",
        "Material specification database",
        "Technical drawings with all structural elements marked",
        "Project-level configuration setup",
      ],
      timeline: "Same day completion for standard residential projects",
    },
  },
  {
    id: "input",
    icon: ClipboardList,
    imgSrc: "/img/checklist.png",
    imgAlt: "data input and requirements",
    title: "Design Input Collection",
    shortDescription: "Gathering comprehensive design requirements including 2D layouts, laminate codes, and technical specifications through detailed consultation.",
    details: {
      overview: "We collect all necessary design inputs from the designer including 2D furniture layouts, laminate preferences, and technical specifications through a structured consultation process.",
      keyActivities: [
        "Collection of 2D furniture layout designs from client",
        "Laminate code selection and specification",
        "Detailed consultation call for technical requirements",
        "Kitchen appliance specifications and integration planning",
      ],
      technicalProcess: [
        "Plywood thickness determination based on application",
        "Edge banding material selection (1mm inner, 2mm exposed)",
        "Hardware and fitting specifications",
        "Special requirements documentation (sliding doors, profile lights, etc.)",
      ],
      qualityControls: [
        "Design feasibility assessment",
        "Material compatibility verification",
        "Structural integrity evaluation",
        "Cost optimization recommendations",
      ],
      deliverables: [
        "Comprehensive design brief document",
        "Material specification sheet",
        "Technical requirements checklist",
        "Project timeline and milestones",
      ],
      timeline: "2-3 days for requirement finalization",
    },
  },
  {
    id: "model",
    icon: Package,
    imgSrc: "/img/automation.png",
    imgAlt: "3D modeling process",
    title: "3D Modeling",
    shortDescription: "Creation of detailed 3D models in Software with precise plank-by-plank specifications, built from scratch using site measurements.",
    details: {
      overview: "Using site measurements and design inputs, we create detailed 3D models of all modular elements in Software, representing the final layout panel by panel with complete technical specifications.",
      keyActivities: [
        "3D modeling of furniture layouts panel by panel using Software",
        "Component creation with precise dimensions and specifications",
        "Material assignment for each surface and edge",
        "Hardware placement and hole specifications",
      ],
      technicalProcess: [
        "Adjacency condition analysis (exposed sides, box sides, wall sides)",
        "Application of edge banding rules based on exposure",
        "VB fitting and screw hole positioning for assembly",
        "Hinge hole standards based on door dimensions and plywood thickness",
      ],
      qualityFeatures: [
        "Plank-level detail with exact dimensions",
        "Material code assignment for each component",
        "Hole specifications for all hardware",
        "Assembly sequence planning",
      ],
      deliverables: [
        "Complete 3D model with all components",
        "Individual plank specifications",
        "Material assignment documentation",
        "Hardware placement drawings",
      ],
      timeline: "3-5 days depending on project complexity",
    },
  },
  {
    id: "design",
    icon: FileText,
    imgSrc: "/img/checklist.png",
    imgAlt: "design documentation",
    title: "Design Finalization",
    shortDescription: "Final design review and approval process with detailed documentation and client confirmation before production begins.",
    details: {
      overview: "We present the complete 3D model and technical specifications for your review and approval, ensuring every detail meets your requirements before moving to production.",
      keyActivities: [
        "3D model presentation and walkthrough",
        "Design review and feedback incorporation",
        "Final specification confirmation",
        "Client approval and sign-off process",
      ],
      reviewProcess: [
        "Virtual model presentation with detailed explanations",
        "Modification requests handling and implementation",
        "Material and finish confirmation",
        "Final cost and timeline confirmation",
      ],
      qualityAssurance: [
        "Design compliance with structural elements",
        "Material availability verification",
        "Production feasibility confirmation",
        "Installation sequence validation",
      ],
      deliverables: [
        "Approved 3D model with all specifications",
        "Final design documentation package",
        "Signed client approval forms",
        "Production-ready technical drawings",
      ],
      timeline: "1-2 days for review and approval",
    },
  },
  {
    id: "estimate",
    icon: Calculator,
    imgSrc: "/img/checklist.png",
    imgAlt: "material estimation",
    title: "Material Estimation",
    shortDescription: "Precise material estimates with detailed cut lists, optimized sheet utilization, and waste minimization calculations.",
    details: {
      overview: "We generate detailed material estimates with precise cut lists that optimize sheet utilization and minimize waste, providing complete transparency in material requirements.",
      estimationProcess: [
        "Plank-by-plank material calculation",
        "Cut list generation with sheet optimization",
        "Waste minimization through nesting algorithms",
        "Material quantity verification and buffer calculations",
      ],
      technicalDetails: [
        "Sheet utilization optimization (8x4 feet standard sheets)",
        "Cutting tool diameter compensation (8mm kerf allowance)",
        "Grain direction considerations for aesthetic panels",
        "Edge banding length calculations",
      ],
      qualityFeatures: [
        "Detailed breakdown showing plank placement on each sheet",
        "Material code tracking for each component",
        "Waste percentage calculations and optimization",
        "Alternative material suggestions for cost optimization",
      ],
      deliverables: [
        "Comprehensive material estimate with quantities",
        "Detailed cut list with sheet layouts",
        "Material procurement guidelines",
        "Cost optimization recommendations",
      ],
      timeline: "2-3 days for detailed estimation",
    },
  },
  {
    id: "check",
    icon: CheckSquare,
    imgSrc: "/img/checklist.png",
    imgAlt: "material quality check process",
    title: "Material Quality Check",
    shortDescription: "Comprehensive quality checks before production begins, including material verification and design validation.",
    details: {
      overview: "Before production begins, we conduct thorough checks to ensure all specifications are correct, materials are available, and the design is production-ready.",
      qualityChecks: [
        "Input Quality Check: Checking for undulations and material abnormalities",
        "Design specification verification against client requirements",
        "Material availability and quality confirmation",
        "Production feasibility assessment",

      ],
      technicalValidation: [
        "Structural integrity analysis",
        "Hardware compatibility verification",
        "Assembly sequence optimization",
        "Installation requirements confirmation",
      ],
      materialVerification: [
        "Laminate code confirmation and availability",
        "Plywood thickness and quality standards",
        "Edge banding material specifications",
      ],
      deliverables: [
        "Material verification certificate",
        "Production readiness confirmation",
        "Final specification sign-off",
      ],
      timeline: "1 day for comprehensive verification",
    },
  },
  {
  id: "verification",
  icon: CheckSquare, // Using a more relevant icon
  imgSrc: "/img/checklist.png",
  imgAlt: "Site verification",
  title: "Site Verification",
  shortDescription: "A final on-site verification to confirm measurements and site conditions against the approved 3D models before production.",
  details: {
    overview: "Our team conducts a final site verification to ensure that the approved designs perfectly match the site's reality, preventing any discrepancies before manufacturing begins.",
    keyActivities: [
      "Cross-referencing final 3D models with on-site measurements.",
      "Verifying positions of electrical points, plumbing, and other utilities.",
      "Checking for any structural changes since the initial measurement.",
    ],
    documentation: [
      "Site verification checklist sign-off.",
      "Annotated photos of the site.",
      "Confirmation report for production.",
      "Client sign-off on final verification.",
    ],
    qualityFeatures: [
      "Ensures 100% accuracy before cutting materials.",
      "Eliminates costly on-site alterations.",
      "Guarantees a perfect fit for all modular units.",
      "Provides final peace of mind for the client.",
    ],
    deliverables: [
      "Signed site verification report.",
      "Go-ahead confirmation for the production team.",
      "Finalized pre-production documentation.",
      "Client confirmation of site readiness.",
    ],
    timeline: "Completed within 1 day after design finalization.",
  },
  },
  {
    id: "payment",
    icon: CreditCard,
    imgSrc: "/img/checklist.png",
    imgAlt: "payment processing",
    title: "Payment Processing",
    shortDescription: "Transparent payment structure with token advance for measurements and staged payments aligned with production milestones.",
    details: {
      overview: "Our transparent payment structure ensures you pay only as work progresses, with clear milestones and no hidden costs.",
      paymentStructure: [
        "₹5,000 token advance for site measurements and pre-production documentation",
        "₹110 per sq ft when material reaches factory for production start",
        "₹110 per sq ft when material is ready for dispatch",
        "Total rate: ₹220 per sq ft (excluding material, packaging, transportation, hamali and GST)",
      ],
      included: [
        "Site measurements with laser precision",
        "Complete pre-production documentation",
        "3D modeling and design services",
        "Factory production and quality control",
      ],
      transparency: [
        "No hidden charges or surprise costs",
        "Clear breakdown of all expenses",
        "Flexible payment options available",
        "GST invoicing for business clients",
      ],
      deliverables: [
        "Detailed cost breakdown and invoice",
        "Payment schedule documentation",
        "Receipt and payment confirmations",
        "GST compliance documentation",
      ],
      timeline: "Immediate processing upon approval",
    },
  },
  
  {
    id: "factory",
    icon: Factory,
    imgSrc: "/img/automation.png",
    imgAlt: "factory production",
    title: "Factory Production",
    shortDescription: "State-of-the-art CNC manufacturing with automated cutting, precision hole drilling, and quality control processes.",
    details: {
      overview: "Once materials arrive at our factory, we conduct thorough input QA before beginning our automated production process using advanced CNC machinery and strict quality control systems.",
      productionStages: [
        "Timeline and resource allocation validation","Pressing Operations: Cold press, hot press, or rolling press based on material type",
        "Automated CNC Cutting: Precise cutting with guaranteed hole placement accuracy",
        "Edge Banding: Application of 1mm or 2mm edge banding as specified",
      ],
      technicalCapabilities: [
        "CNC machines with 10-tool capacity for various operations",
        "Automated hole drilling for hinges, screws, and VB fittings",
        "Profile light cutting and specialized groove creation",
        "Nesting optimization for maximum sheet utilization",
      ],
      qualityAssurance: [
        "Automated machinery ensures no misplaced holes",
        "Continuous quality monitoring throughout production",
        "Dimensional accuracy verification at each stage",
        "Surface finish quality control",
      ],
      deliverables: [
        "Precision-cut components with all specifications",
        "Production progress reports",
        "Component identification and labeling",
      ],
      timeline: "14 working days from material receipt to completion of production",
    },
  },
  {
    id: "packing",
    icon: PackageOpen,
    imgSrc: "/img/installation.png",
    imgAlt: "packaging process",
    title: "Quality Packing",
    shortDescription: "Systematic unit-wise packaging with installation-optimized organization and comprehensive quality checks.",
    details: {
      overview: "After production, all components undergo final quality checks and are systematically packed unit-wise for easy installation, with each package clearly labeled and organized.",
      packagingProcess: [
        "Final quality inspection of all components",
        "Unit-wise segregation and organization",
        "Installation-sequence based packaging",
        "Protective packaging for transportation",
      ],
      qualityFeatures: [
        "Each package contains all components for one unit",
        "Clear labeling with component identification",
        "Installation guide inclusion in each package",
      ],
      organizationSystem: [
        "Component identification labels on each piece",
        "Installation sequence numbering",
        "Assembly instruction cards for each unit",
      ],
      deliverables: [
        "Installation-ready packaged units",
        "Component identification documentation",
        "Packaging list with contents verification",
        "Transportation and handling guidelines",
      ],
      timeline: "1-2 days for complete packaging",
    },
  },
  {
    id: "dispatch",
    icon: Truck,
    imgSrc: "/img/installation.png",
    imgAlt: "dispatch and logistics",
    title: "Dispatch & Logistics",
    shortDescription: "Coordinated dispatch with 3rd-party transportation arrangements and delivery scheduling to ensure timely arrival at your site.",
    details: {
      overview: "We coordinate the dispatch of your packaged units with proper 3rd-party transportation arrangements, ensuring timely delivery to your site with all necessary documentation.",
      logisticsProcess: [
        "3rd-party Transportation arrangement and vehicle selection",
        "Delivery scheduling coordination with client",
      ],
      documentation: [
        "Dispatch documentation with complete inventory",
        "Transportation receipts and tracking information",
        "Delivery confirmation and sign-off procedures",
      ],
      qualityAssurance: [
        "Delivery time coordination with installation team",
        "Condition verification upon delivery",
      ],
      deliverables: [
        "Complete packaged units delivered to site",
        "Dispatch and delivery documentation",
        "Delivery confirmation receipts",
      ],
      timeline: "1-3 days depending on location and logistics",
    },
  },
  {
    id: "install",
    icon: Wrench,
    imgSrc: "/img/installation.png",
    imgAlt: "professional installation",
    title: "Professional Installation",
    shortDescription: "Expert installation support with detailed guides, on-site engineering assistance, and professional carpentry teams available.",
    details: {
      overview: "Our installation phase ensures seamless assembly of your modular furniture with professional support, detailed guides, and quality assurance throughout the process.",
      installationOptions: [
        "Detailed installation guides for teams with basic carpentry skills",
        "On-site engineer training and supervision available",
        "Professional carpentry teams available for hire",
        "Hybrid fitting approach combining screw and VB-fitting systems for optimal results",
      ],
      supportServices: [
        "Site engineer deployment for team training and guidance",
        "Step-by-step installation documentation with illustrations",
        "Quality control monitoring during installation process",
        "Post-installation support and troubleshooting",
      ],
      qualityFeatures: [
        "Installation-optimized packaging for easy site handling",
        "Component identification system for efficient assembly",
        "Precision-cut components requiring minimal on-site adjustments",
        "Professional finishing with attention to detail",
      ],
      transparency: [
        "Open factory policy for existing customers to visit anytime",
        "Material tracking and verification system throughout process",
        "Regular progress updates during production and installation",
        "Direct customer supervision opportunities at every stage",
      ],
      deliverables: [
        "Fully installed modular furniture units",
        "Installation completion certificates",
        "Maintenance and care instructions",
        "Warranty documentation and support contacts",
      ],
      timeline: "Varies based on project size and complexity",
    },
  },
]

export const pricingInfo = {
  rate: "₹220 per sq ft",
  includes: ["Site measurements", "Pre-production documentation", "Factory production"],
  excludes: ["Material costs", "Packaging", "Transportation","Hamali", "GST"],
  paymentStructure: [
    "₹5,000 token advance for site measurements and pre-production",
    "₹110 per sq ft when material reaches factory",
    "₹110 per sq ft when material is ready for dispatch",
  ],
}
