export enum RoleCode { }

export const ENVIRONMENTS = {
  LOCAL: "LOCAL",
  DEVELOPMENT: "DEVELOPMENT",
  TEST: "TEST",
  PRODUCTION: "PRODUCTION",
};

export const NOT_FOUND_DATABASE_ERRORS = {
  DATABASE_NOT_FOUND: "DATABASE NOT FOUND",
  DATA_NOT_FOUND: "DATA NOT FOUND",
  ROLE_NOT_FOUND_FOR_GROUP: "ROLE NOT FOUND FOR GROUP",
  GROUP_NOT_FOUND_FOR_ROLE: "GROUP NOT FOUND FOR ROLE",
  GROUP_NOT_FOUND_FOR_CAMPAIGN: "GROUP NOT FOUND FOR CAMPAIGN",
  CAMPAIGN_NOT_FOUND_FOR_GROUP: "CAMPAIGN NOT FOUND FOR GROUP",
  USER_NOT_FOUND_FOR_GROUP: "USER NOT FOUND FOR GROUP",
  GROUP_NOT_FOUND_FOR_USER: "GROUP NOT FOUND FOR USER",
  ROLE_NOT_FOUND_FOR_USER: "ROLE NOT FOUND FOR USER",
  USER_NOT_FOUND_FOR_ROLE: "USER NOT FOUND FOR ROLE",
  GROUP_NOT_FOUND_FOR_TEMPLATE: "GROUP NOT FOUND FOR TEMPLATE",
  TEMPLATE_NOT_FOUND_FOR_GROUP: "TEMPLATE NOT FOUND FOR GROUP",
  PERMISSION_NOT_FOUND_FOR_TEMPLATE: "PERMISSION NOT FOUND FOR TEMPLATE",
  TEMPLATE_NOT_FOUND_FOR_PERMISSION: "TEMPLATE NOT FOUND FOR PERMISSION",
}

export const BAD_REQUEST_ERRORS = {
  INVALID_PATH: "INVALID PATH",
  INVALID_ID: "INVALID_ID",
  INVALID_QUERY: "INVALID_QUERY",
  INVALID_DATA: "INVALID_DATA"
}
export const LOGGER_MSG_ICONS = {
  error: "📕",
  warn: "📙",
  info: "📗",
  unknown: "🔘",
};

export const TABLES = {
  USER_ROLE_MAPPING: "UserRoleMapping",
  GROUP_TEMPLATE_MAPPING : "GroupTemplateMapping",
  ADDRESS_USER_MAPPING : "AddressUserMapping",
  USER_GROUP_MAPPING : "UserGroupMapping",
  PERMISSION_TEMPLATE_MAPPING : "PermissionTemplateMapping",
  CAMPAIGN_GROUP_MAPPING : "CampaignGroupMapping",
}

export const GENERIC_ERROR = "UMS INTERNAL SERVER ERROR";

export const LOGGER_MSG_COLORS = {
  error: "bold red",
  warn: "italic yellow",
  info: "bold blue",
};