export const PROJECT_STATUS = {
  DRAFT: 1,
  ACTIVE: 2,
  ARCHIVED: 3,
  COMPLETED: 4, // Assuming this might exist or be added later
};

export const PROJECT_STATUS_TRANSITIONS = {
  [PROJECT_STATUS.DRAFT]: [PROJECT_STATUS.ACTIVE, PROJECT_STATUS.ARCHIVED],
  [PROJECT_STATUS.ACTIVE]: [PROJECT_STATUS.ARCHIVED, PROJECT_STATUS.COMPLETED],
  [PROJECT_STATUS.ARCHIVED]: [PROJECT_STATUS.ACTIVE], // Or perhaps only to Draft?
  [PROJECT_STATUS.COMPLETED]: [PROJECT_STATUS.ARCHIVED], // Or no transitions from completed
};
