import { PrismaClient, ModelBomItem } from '@prisma/client';
import { JavaScriptFunctionService } from '../../catalogue/services/javascript-function.service';
import { GLOBAL_CONSTANTS } from '../../catalogue/config/globalConstants'; // Import centralized constants

interface PlankGenerationContext {
    boxNumber: string;
    modelDefinitionId: string;
    inputs: Record<string, any>;
}

interface GeneratedPlank {
  width: number;
  length: number; // Was 'height'
  materialCode: string;
  plankId: string; // This will be the fully constructed ID: BoxNumber + PacketNumber + PlankIdentifier
  holes: Array<{x: number, y: number, z: number, t: number}>;
  grooves: Array<{x1: number, y1: number, x2: number, y2: number, z: number, t: number}>;
  // name?: string; // Optional: if the script returns a name for the plank
}

export class PlankGenerationService {
    private prisma: PrismaClient;
    private jsFunctionService: JavaScriptFunctionService;

    constructor() {
        this.prisma = new PrismaClient();
        this.jsFunctionService = new JavaScriptFunctionService(); // Instantiate the service
    }

    async generatePlanksForBox(context: PlankGenerationContext): Promise<GeneratedPlank[]> {
        try {
            // Fetch the model definition and its BOM items
            const modelDefinition = await this.prisma.modelDefinition.findUnique({
                where: { id: context.modelDefinitionId },
                include: {
                    bomItems: {
                        where: { itemType: 'PLANK' }
                    }
                }
            });

            if (!modelDefinition) {
                throw new Error(`Model definition ${context.modelDefinitionId} not found`);
            }

            const planks: GeneratedPlank[] = [];

            // Process each BOM item that is a plank
            for (const bomItem of modelDefinition.bomItems as ModelBomItem[]) { // Cast to ModelBomItem
                // The itemLogicScript is the full function string generated by the frontend
                const script = bomItem.itemLogicScript;
                if (!script) {
                    console.warn(`Skipping BOM item ${bomItem.itemName} due to missing itemLogicScript`);
                    continue;
                }

                // Execute the script using JavaScriptFunctionService
                const calculatedProps = await this.jsFunctionService.executeItemScript(
                    script,
                    { runtimeInputs: context.inputs, globalConstants: GLOBAL_CONSTANTS } // Use imported GLOBAL_CONSTANTS
                );

                if (!calculatedProps || typeof calculatedProps.width === 'undefined') {
                     console.warn(`Skipping BOM item ${bomItem.itemName} due to invalid script execution result:`, calculatedProps);
                    continue;
                }
                
                // Construct the final plankId
                // plankIdPart should be like "P1LT" (PacketNumber + PlankIdentifier)
                const plankId = `${context.boxNumber}${calculatedProps.plankIdPart}`;

                const plank: GeneratedPlank = {
                    plankId: plankId,
                    width: calculatedProps.width,
                    length: calculatedProps.length, // Ensure this matches the property name returned by the script
                    materialCode: calculatedProps.materialCode,
                    holes: calculatedProps.holes || [],
                    grooves: calculatedProps.grooves || []
                    // name: calculatedProps.name // Optional: if the script returns a name
                };
                planks.push(plank);
            }
            return planks;

        } catch (error) {
            console.error('Error generating planks for box:', error);
            throw error;
        }
    }

    async generatePlanksForProject(projectId: number): Promise<GeneratedPlank[]> {
        try {
            const modelInstances = await this.prisma.projectModelInstance.findMany({
                where: { projectId },
                orderBy: { uiDisplayOrder: 'asc' },
                include: { 
                    // Eager load modelDefinition and its bomItems with details
                    modelDefinition: {
                        include: {
                            bomItems: {
                                where: { itemType: 'PLANK' }
                            }
                        }
                    }
                }
            });

            const allPlanks: GeneratedPlank[] = [];

            for (const instance of modelInstances) {
                const boxNumber = (instance.uiDisplayOrder + 1).toString().padStart(2, '0');
                
                if (!instance.modelDefinition || !instance.modelDefinition.bomItems) {
                    console.warn(`Skipping instance ${instance.id} due to missing model definition or BOM items.`);
                    continue;
                }

                for (const bomItem of instance.modelDefinition.bomItems as ModelBomItem[]) {
                    const script = bomItem.itemLogicScript;
                    if (!script) {
                        console.warn(`Skipping BOM item ${bomItem.itemName} in box ${boxNumber} due to missing script.`);
                        continue;
                    }

                    try {
                        const calculatedProps = await this.jsFunctionService.executeItemScript(
                            script,
                            { 
                                runtimeInputs: instance.runtimeInputsJson as Record<string, any>, 
                                globalConstants: GLOBAL_CONSTANTS // Use imported GLOBAL_CONSTANTS
                            }
                        );

                        if (!calculatedProps || typeof calculatedProps.width === 'undefined') {
                            console.warn(`Invalid script result for ${bomItem.itemName} in box ${boxNumber}:`, calculatedProps);
                            continue;
                        }

                        const plankId = `${boxNumber}${calculatedProps.plankIdPart}`;
                        allPlanks.push({
                            plankId,
                            width: calculatedProps.width,
                            length: calculatedProps.length,
                            materialCode: calculatedProps.materialCode,
                            holes: calculatedProps.holes || [],
                            grooves: calculatedProps.grooves || [],
                        });
                    } catch (scriptError) {
                        console.error(`Error executing script for ${bomItem.itemName} in box ${boxNumber}:`, scriptError);
                        // Optionally, decide if one script error should halt all plank generation or just skip this plank
                    }
                }
            }
            return allPlanks;
        } catch (error) {
            console.error('Error generating planks for project:', error);
            throw error;
        }
    }

    // executeBomItemLogicScript is no longer needed as its logic is integrated into generatePlanksForProject
    // and generatePlanksForBox (if we decide to keep it separate for single box generation later)
}
